heat_template_version: 2015-10-15

description: Launch a basic instance with classic networking

parameters:
  name:
    type: string
    label: Name
    description: Name prefix.

  count:
    type: number
    label: Count
    description: Number of servers to create.
    default: 1

  image:
    type: string
    label: Image
    description: Image to be used for instances.

  flavor:
    type: string
    label: Flavor
    description: Flavor to be used on the instances.

  key:
    type: string
    label: Key name
    description: Name of key-pair to be installed on the instances.

  net_id:
    type: string
    label: Network
    description: Provider network id.

  security:
    type: comma_delimited_list
    label: SecurityGroup
    description: Instance security groups.
    default: [ 'default' ]

  az:
    type: string
    label: Availability Zone
    description: Availability zone.


resources:
  suffix:
    type: OS::Heat::RandomString
    properties:
      character_classes: [{'class': 'hexdigits', 'min': 8}]
      length: 8

  servers:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: count }
      resource_def:
        type: OS::Nova::Server
        properties:
          name:
            list_join: ['-', [{ get_param: name }, { get_resource: suffix }, 'inst', '%index%']]
          image: { get_param: image }
          flavor: { get_param: flavor }
          key_name: { get_param: key }
          availability_zone: { get_param: az }
          networks:
            - network: { get_param: net_id }
          security_groups: { get_param: security }

outputs:
  instance_names:
    description: instance names.
    value: { get_attr: [ servers, name ] }
  instance_ips:
    description: instance addresses.
    value: { get_attr: [ servers, first_address ] }
  instance_uuids:
    description: instance uuids.
    value: { get_attr: [ servers, refs ] }
